import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { setupPromisePolyfill } from "@/lib/promise-polyfill";
import { AnnotationProvider } from "@/components/context_panel/annotations/AnnotationProvider";

// Initialize Promise.withResolvers polyfill
setupPromisePolyfill();

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Preload the PDF worker script for better performance */}
        <link 
          rel="preload" 
          href="/pdf-worker/pdf.worker.min.mjs" 
          as="script" 
          crossOrigin="anonymous" 
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <AnnotationProvider>
          {children}
        </AnnotationProvider>
      </body>
    </html>
  );
}
